on: [push, pull_request]
name: Test

jobs:
  test-nocache:
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        cache: false

    # Datadog: wrap job execution
    - name: Run tests with Datadog visibility
      uses: DataDog/datadog-actions-ci@v1
      with:
        api_key: ${{ secrets.DD_API_KEY }}
        site: datadoghq.com   # use datadoghq.eu if in EU
        command: go test ./...

  test-cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: 1.21.x

    # Datadog: wrap job execution
    - name: Run tests with Datadog visibility
      uses: DataDog/datadog-actions-ci@v1
      with:
        api_key: ${{ secrets.DD_API_KEY }}
        site: datadoghq.com
        command: go test ./...
